### PR TITLE
fixes #3; match var names in README & index.html

### LINKED ISSUE #3: Cannot read property 'length' of undefined
This bug occurs when a repeat command is executed with N = 0 (e.g. `repeat 1 0`).

It occurs on [src/interpreter.js#L81](https://github.com/wgreenberg/quine.zip/blob/gh-pages/src/interpreter.js#L81). In [this code block](https://github.com/wgreenberg/quine.zip/blob/gh-pages/src/interpreter.js#L97), `start` ends up equaling 1 because `outputLines` is an array of 1 item and `instructions.b` is 0. Because `start` is 1, the loop is accessing `outputLines[1]`, which is `undefined` because `outputLines` has only 1 item, but the value still gets pushed to `outputLines`. `program` at that point is an empty array, so [src/interpreter#L90](https://github.com/wgreenberg/quine.zip/blob/gh-pages/src/interpreter.js#L90) gets executed. Remember that `outputLines` is an array of `[/*previous action {String}*/, undefined]`. Now we're back at [src/interpreter.js#L81](https://github.com/wgreenberg/quine.zip/blob/gh-pages/src/interpreter.js#L81), where `undefined.length` throws the error.

Hopefully that made sense...
Here are some examples that throw the error:

``` js
print 1
print 1
repeat 1 0

// OR

print 2
print 1
print 1
repeat 3 0

// OR

print 1
print 3
repeat 2 0
print 2
```

### PR DESCRIPTION
**Pull request by shaheenp**
fixes #3 

Solution:
- check if M is a whole number (e.g. 0, 1, 2, ...)
- check if N is a natural number (e.g. 1, 2, 3, ...)

Also, the variable names in the README's instructions were different than the ones in index.html so I synced them up.

### CODE REVIEW

File: src/interpreter.js [hunk 1]
```diff
@@ -60,13 +60,20 @@ function getParser (instructionSet) {
...
-function parseNat (str) {
+function parseWhole (str) {
     if(/^[0-9]+$/.test(str)) {
         return Number(str);
     }
     return NaN;
 }
 
+function parseNat (str) {
+    if(/^[0-9]+$/.test(str) && Number(str) !== 0) {
```
Comment (wgreenberg) [inline src/interpreter.js]: how about just:

```
var whole = parseWhole(str);
return whole === 0 ? NaN : whole;
```

to avoid code duplication?

**Comment by shaheenp** [comment]
@wgreenberg good call
